-- MySifa : import données paie historiques (janv–mars 2026)
-- Généré automatiquement — à exécuter UNE SEULE FOIS sur le VPS
PRAGMA foreign_keys = OFF;
BEGIN TRANSACTION;

-- ── Tables paie ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS paie_employes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER UNIQUE, matricule TEXT,
    contrat_type TEXT DEFAULT 'CDI',
    date_debut TEXT, date_fin TEXT,
    nb_heures_base REAL, taux_horaire REAL,
    salaire_mensuel REAL, prime_anciennete REAL,
    mutuelle INTEGER DEFAULT 0, avantage_voiture REAL,
    updated_at TEXT, updated_by TEXT,
    FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS paie_variables (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    annee INTEGER NOT NULL, mois INTEGER NOT NULL,
    data TEXT NOT NULL DEFAULT '{}',
    updated_at TEXT NOT NULL, updated_by TEXT,
    UNIQUE(user_id, annee, mois),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- ── Employés sans compte MySifa (inactifs, paie uniquement) ─────────────
INSERT OR IGNORE INTO users(nom, email, password_hash, role, actif, identifiant, created_at) VALUES ('Laurent Woronin', 'paie_laurent.woronin@sifa.local', '', 'fabrication', 0, 'laurent.woronin', '2026-04-27T07:24:24.447829');
INSERT OR IGNORE INTO users(nom, email, password_hash, role, actif, identifiant, created_at) VALUES ('Patrice Granger', 'paie_patrice.granger@sifa.local', '', 'fabrication', 0, 'patrice.granger', '2026-04-27T07:24:24.447829');
INSERT OR IGNORE INTO users(nom, email, password_hash, role, actif, identifiant, created_at) VALUES ('Jonathan Celisse', 'paie_jonathan.celisse@sifa.local', '', 'fabrication', 0, 'jonathan.celisse', '2026-04-27T07:24:24.447829');
INSERT OR IGNORE INTO users(nom, email, password_hash, role, actif, identifiant, created_at) VALUES ('Valentin Larguinho', 'paie_valentin.larguinho@sifa.local', '', 'fabrication', 0, 'valentin.larguinho', '2026-04-27T07:24:24.447829');
INSERT OR IGNORE INTO users(nom, email, password_hash, role, actif, identifiant, created_at) VALUES ('Mohamed Ali Tahir', 'paie_mohamed.tahir@sifa.local', '', 'fabrication', 0, 'mohamed.tahir', '2026-04-27T07:24:24.447829');
INSERT OR IGNORE INTO users(nom, email, password_hash, role, actif, identifiant, created_at) VALUES ('Mostafa El Hammouchi', 'paie_mostafa.el@sifa.local', '', 'fabrication', 0, 'mostafa.el', '2026-04-27T07:24:24.447829');
INSERT OR IGNORE INTO users(nom, email, password_hash, role, actif, identifiant, created_at) VALUES ('Cyril Cordonnier', 'paie_cyril.cordonnier@sifa.local', '', 'fabrication', 0, 'cyril.cordonnier', '2026-04-27T07:24:24.447829');
INSERT OR IGNORE INTO users(nom, email, password_hash, role, actif, identifiant, created_at) VALUES ('Jarod Vanhelstraeten', 'paie_jarod.vanhelstraeten@sifa.local', '', 'fabrication', 0, 'jarod.vanhelstraeten', '2026-04-27T07:24:24.447829');
INSERT OR IGNORE INTO users(nom, email, password_hash, role, actif, identifiant, created_at) VALUES ('Naoumi Boubker', 'paie_naoumi.boubker@sifa.local', '', 'fabrication', 0, 'naoumi.boubker', '2026-04-27T07:24:24.447829');
INSERT OR IGNORE INTO users(nom, email, password_hash, role, actif, identifiant, created_at) VALUES ('Saïd Daci', 'paie_said.daci@sifa.local', '', 'fabrication', 0, 'said.daci', '2026-04-27T07:24:24.447829');
INSERT OR IGNORE INTO users(nom, email, password_hash, role, actif, identifiant, created_at) VALUES ('Laetitia Deffrenne', 'paie_laetitia.deffrenne@sifa.local', '', 'fabrication', 0, 'laetitia.deffrenne', '2026-04-27T07:24:24.447829');
INSERT OR IGNORE INTO users(nom, email, password_hash, role, actif, identifiant, created_at) VALUES ('Mickael Adyns', 'paie_mickael.adyns@sifa.local', '', 'fabrication', 0, 'mickael.adyns', '2026-04-27T07:24:24.447829');
INSERT OR IGNORE INTO users(nom, email, password_hash, role, actif, identifiant, created_at) VALUES ('Henri Mayeur', 'paie_henri.mayeur@sifa.local', '', 'fabrication', 0, 'henri.mayeur', '2026-04-27T07:24:24.447829');
INSERT OR IGNORE INTO users(nom, email, password_hash, role, actif, identifiant, created_at) VALUES ('Réquia Lgarch', 'paie_requia.lgarch@sifa.local', '', 'fabrication', 0, 'requia.lgarch', '2026-04-27T07:24:24.447829');
INSERT OR IGNORE INTO users(nom, email, password_hash, role, actif, identifiant, created_at) VALUES ('Djamal Bouferkas', 'paie_djamal.bouferkas@sifa.local', '', 'fabrication', 0, 'djamal.bouferkas', '2026-04-27T07:24:24.447829');
INSERT OR IGNORE INTO users(nom, email, password_hash, role, actif, identifiant, created_at) VALUES ('Laura Ratz', 'paie_laura.ratz@sifa.local', '', 'fabrication', 0, 'laura.ratz', '2026-04-27T07:24:24.447829');
INSERT OR IGNORE INTO users(nom, email, password_hash, role, actif, identifiant, created_at) VALUES ('Guillaume Granger', 'paie_guillaume.granger@sifa.local', '', 'fabrication', 0, 'guillaume.granger', '2026-04-27T07:24:24.447829');
INSERT OR IGNORE INTO users(nom, email, password_hash, role, actif, identifiant, created_at) VALUES ('Géraldine Themond', 'paie_geraldine.themond@sifa.local', '', 'fabrication', 0, 'geraldine.themond', '2026-04-27T07:24:24.447829');
INSERT OR IGNORE INTO users(nom, email, password_hash, role, actif, identifiant, created_at) VALUES ('Maxime Allouchery', 'paie_maxime.allouchery@sifa.local', '', 'fabrication', 0, 'maxime.allouchery', '2026-04-27T07:24:24.447829');
INSERT OR IGNORE INTO users(nom, email, password_hash, role, actif, identifiant, created_at) VALUES ('Hamza Bachouchi', 'paie_hamza.bachouchi@sifa.local', '', 'fabrication', 0, 'hamza.bachouchi', '2026-04-27T07:24:24.447829');
INSERT OR IGNORE INTO users(nom, email, password_hash, role, actif, identifiant, created_at) VALUES ('Antoine Morel', 'paie_antoine.morel@sifa.local', '', 'fabrication', 0, 'antoine.morel', '2026-04-27T07:24:24.447829');
INSERT OR IGNORE INTO users(nom, email, password_hash, role, actif, identifiant, created_at) VALUES ('Bastien Vernisse', 'paie_bastien.vernisse@sifa.local', '', 'fabrication', 0, 'bastien.vernisse', '2026-04-27T07:24:24.447829');
INSERT OR IGNORE INTO users(nom, email, password_hash, role, actif, identifiant, created_at) VALUES ('Joshua Mutombo', 'paie_joshua.mutombo@sifa.local', '', 'fabrication', 0, 'joshua.mutombo', '2026-04-27T07:24:24.447829');
INSERT OR IGNORE INTO users(nom, email, password_hash, role, actif, identifiant, created_at) VALUES ('Amine Hubert', 'paie_amine.hubert@sifa.local', '', 'fabrication', 0, 'amine.hubert', '2026-04-27T07:24:24.447829');
INSERT OR IGNORE INTO users(nom, email, password_hash, role, actif, identifiant, created_at) VALUES ('Tony Cathelineau', 'paie_tony.cathelineau@sifa.local', '', 'fabrication', 0, 'tony.cathelineau', '2026-04-27T07:24:24.447829');

-- ── paie_employes (données fixes) ───────────────────────────────────────
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Eugene Leconte' LIMIT 1), NULL, 'CDD', '2025-12-11', NULL, NULL, NULL, 3000.0, NULL, 0, NULL, NULL, NULL);  -- Eugene Leconte
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Alan Denis' LIMIT 1), NULL, 'CDI', '2019-08-04', NULL, NULL, NULL, 2300.0, 0.03, 'Non', NULL, NULL, NULL);  -- Alan Denis
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Fatiha Mehdi' LIMIT 1), NULL, 'CDI', '2020-09-03', NULL, NULL, NULL, 2200.0, 0.03, 'Non', NULL, NULL, NULL);  -- Fatiha Mehdi
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Grégory Desreumaux' LIMIT 1), NULL, 'CDI', '17/5/2018', NULL, NULL, NULL, 3750.0, 0.03, 'Oui', NULL, NULL, NULL);  -- Grégory Desreumaux
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Manuel Lesaffre' LIMIT 1), NULL, 'CDI', '27/8/2014', NULL, NULL, NULL, 4434.0, 0.09, 'Non', NULL, NULL, NULL);  -- Manuel Lesaffre
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Laurent Woronin' LIMIT 1), NULL, 'CDI', '2012-07-02', NULL, NULL, NULL, 2147.46, 0.12, 'Oui', NULL, NULL, NULL);  -- Laurent Woronin
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Patrice Granger' LIMIT 1), NULL, 'CDI', '2018-01-01', NULL, NULL, NULL, 7358.0, 0.06, 'Non', NULL, NULL, NULL);  -- Patrice Granger
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Jonathan Celisse' LIMIT 1), NULL, 'CDI', '2018-03-04', NULL, NULL, NULL, 3000.0, 0.03, 'Non', NULL, NULL, NULL);  -- Jonathan Celisse
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Valentin Larguinho' LIMIT 1), NULL, 'CDI', '2018-09-07', NULL, NULL, NULL, 2100.0, 0.03, 'Oui', NULL, NULL, NULL);  -- Valentin Larguinho
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Mohamed Ali Tahir' LIMIT 1), NULL, 'CDI', '2021-06-04', NULL, NULL, NULL, 1950.0, 0.03, 'Non', NULL, NULL, NULL);  -- Mohamed Ali Tahir
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Mostafa El Hammouchi' LIMIT 1), NULL, 'CDI', '2021-01-07', NULL, NULL, NULL, 1950.0, 0.03, 'Non', NULL, NULL, NULL);  -- Mostafa El Hammouchi
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Cyril Cordonnier' LIMIT 1), NULL, 'CDI', '15/11/2021', NULL, NULL, NULL, 2200.0, 0.03, 'Non', NULL, NULL, NULL);  -- Cyril Cordonnier
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Jarod Vanhelstraeten' LIMIT 1), NULL, 'CDI', '15/12/2021', NULL, NULL, NULL, 2147.46, 0.03, 'Oui', NULL, NULL, NULL);  -- Jarod Vanhelstraeten
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Naoumi Boubker' LIMIT 1), NULL, 'CDI', '2022-04-04', NULL, NULL, NULL, 1950.0, 0.03, 'Non', NULL, NULL, NULL);  -- Naoumi Boubker
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Saïd Daci' LIMIT 1), NULL, 'CDI', '21/6/2022', NULL, NULL, NULL, 2200.0, 0.03, 'Oui', NULL, NULL, NULL);  -- Saïd Daci
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Laetitia Deffrenne' LIMIT 1), NULL, 'CDI', '22/8/2022', NULL, NULL, NULL, 2600.0, 0.03, 'Non', NULL, NULL, NULL);  -- Laetitia Deffrenne
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Mickael Adyns' LIMIT 1), NULL, 'CDI', '2022-02-11', NULL, NULL, NULL, 1972.0, 0.03, 'Non', NULL, NULL, NULL);  -- Mickael Adyns
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Henri Mayeur' LIMIT 1), NULL, 'CDI', '13/12/2022', NULL, NULL, NULL, 2300.0, 0.03, 'Oui', NULL, NULL, NULL);  -- Henri Mayeur
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Réquia Lgarch' LIMIT 1), NULL, 'CDI', '2023-01-02', NULL, NULL, NULL, 2200.0, NULL, 'Non', NULL, NULL, NULL);  -- Réquia Lgarch
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Djamal Bouferkas' LIMIT 1), NULL, 'CDI', '2023-05-06', NULL, NULL, NULL, 1809.0, NULL, 'Non', NULL, NULL, NULL);  -- Djamal Bouferkas
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Laura Ratz' LIMIT 1), NULL, 'CDI', '2023-01-07', NULL, NULL, NULL, 2350.0, NULL, 'Non', NULL, NULL, NULL);  -- Laura Ratz
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Guillaume Granger' LIMIT 1), NULL, 'CDI', '2024-08-04', NULL, NULL, NULL, 2650.0, NULL, 'Oui', NULL, NULL, NULL);  -- Guillaume Granger
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Géraldine Themond' LIMIT 1), NULL, 'CDI', '28/8/2024', NULL, NULL, NULL, 2750.0, NULL, 'Oui', NULL, NULL, NULL);  -- Géraldine Themond
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Maxime Allouchery' LIMIT 1), NULL, 'CDI', '28/4/2025', NULL, NULL, NULL, 1867.0, NULL, 'Non', NULL, NULL, NULL);  -- Maxime Allouchery
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Hamza Bachouchi' LIMIT 1), NULL, 'CDI', '28/8/2025', NULL, NULL, NULL, 2300.0, NULL, 'Non', NULL, NULL, NULL);  -- Hamza Bachouchi
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Antoine Morel' LIMIT 1), NULL, 'CDI', '2025-06-10', NULL, NULL, NULL, 1867.0, NULL, 'non', NULL, NULL, NULL);  -- Antoine Morel
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Bastien Vernisse' LIMIT 1), NULL, 'CDI', '2025-09-10', NULL, NULL, NULL, 2300.0, NULL, 'non', NULL, NULL, NULL);  -- Bastien Vernisse
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Joshua Mutombo' LIMIT 1), NULL, 'CDD', '2026-11-02', NULL, NULL, NULL, 1809.0, NULL, 0, NULL, NULL, NULL);  -- Joshua Mutombo
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Amine Hubert' LIMIT 1), NULL, 'CDD', '2026-09-02', NULL, NULL, NULL, 1809.0, NULL, 0, NULL, NULL, NULL);  -- Amine Hubert
INSERT OR IGNORE INTO paie_employes (user_id, matricule, contrat_type, date_debut, date_fin, nb_heures_base, taux_horaire, salaire_mensuel, prime_anciennete, mutuelle, avantage_voiture, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Tony Cathelineau' LIMIT 1), NULL, 'CDI', '16/2/2026', NULL, NULL, NULL, 2558.0, NULL, 0, NULL, NULL, NULL);  -- Tony Cathelineau

-- ── paie_variables (données mensuelles) ──────────────────────────────────
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Alan Denis' LIMIT 1), 2026, 1, '{"heures_sup_25": "1H50", "prime_equipe": 30.0, "absence_maladie_jours": "12 ET 13/01", "absence_cp_jours": "2026-02-01"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Alan Denis
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Antoine Morel' LIMIT 1), 2026, 1, '{"prime_equipe": "30 euros", "absence_maladie_jours": "DU 05 AU 20"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Antoine Morel
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Bastien Vernisse' LIMIT 1), 2026, 1, '{"heures_sup_25": "15H50", "prime_equipe": "30 euros", "absence_cp_jours": "2026-02-01"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Bastien Vernisse
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Cyril Cordonnier' LIMIT 1), 2026, 1, '{"absence_cp_jours": "2026-02-01"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Cyril Cordonnier
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Djamal Bouferkas' LIMIT 1), 2026, 1, '{"prime_equipe": 30.0, "absence_cp_jours": "LE 2 ET LE 22"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Djamal Bouferkas
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Eugene Leconte' LIMIT 1), 2026, 1, '{"absence_cp_jours": "2026-02-01"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Eugene Leconte
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Fatiha Mehdi' LIMIT 1), 2026, 1, '{"absence_cp_jours": "2026-02-01", "acompte_exceptionnel": 600.29}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Fatiha Mehdi
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Grégory Desreumaux' LIMIT 1), 2026, 1, '{"absence_cp_jours": "2026-02-01"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Grégory Desreumaux
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Guillaume Granger' LIMIT 1), 2026, 1, '{"commissions_ventes": 850.88}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Guillaume Granger
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Géraldine Themond' LIMIT 1), 2026, 1, '{"absence_cp_jours": "2026-02-01", "acompte_exceptionnel": 500.0}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Géraldine Themond
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Hamza Bachouchi' LIMIT 1), 2026, 1, '{"prime_equipe": "30 euros", "absence_cp_jours": "2026-02-01", "absence_css_jours": "8-26-27-28-30", "absence_justifiee_np_h": "7H"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Hamza Bachouchi
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Henri Mayeur' LIMIT 1), 2026, 1, '{"prime_equipe": 30.0, "absence_cp_jours": "2026-01-02"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Henri Mayeur
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Jarod Vanhelstraeten' LIMIT 1), 2026, 1, '{"absence_maladie_jours": "6-7-8-9", "absence_cp_jours": "02 ET 05/01", "mi_temps_therapeutique": "52H30"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Jarod Vanhelstraeten
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Jonathan Celisse' LIMIT 1), 2026, 1, '{"heures_sup_25": "8H10", "prime_equipe": 30.0, "absence_cp_jours": "2026-02-01", "pret_sifa": 200.0, "acompte_exceptionnel": 500.15}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Jonathan Celisse
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Laetitia Deffrenne' LIMIT 1), 2026, 1, '{"absence_maladie_jours": "15-16-19-20-26", "absence_cp_jours": "2026-02-01"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Laetitia Deffrenne
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Laura Ratz' LIMIT 1), 2026, 1, '{"absence_cp_jours": "LE 2 ET LE 16"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Laura Ratz
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Laurent Woronin' LIMIT 1), 2026, 1, '{"prime_equipe": 30.0, "absence_cp_jours": "2026-02-01"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Laurent Woronin
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Manuel Lesaffre' LIMIT 1), 2026, 1, '{"prime_objectifs": 400.0}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Manuel Lesaffre
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Maxime Allouchery' LIMIT 1), 2026, 1, '{"heures_sup_25": "12H40", "prime_equipe": "30 euros", "absence_cp_jours": "LE 02 ET LE 21"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Maxime Allouchery
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Mickael Adyns' LIMIT 1), 2026, 1, '{"prime_equipe": 30.0, "absence_maladie_jours": "19-20-21", "absence_cp_jours": "2026-01-02", "absence_css_jours": "LE 6", "acompte_exceptionnel": 500.0}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Mickael Adyns
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Mohamed Ali Tahir' LIMIT 1), 2026, 1, '{"heures_sup_25": "9H", "prime_equipe": 30.0, "absence_cp_jours": "2026-02-01", "acompte_exceptionnel": 1050.29}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Mohamed Ali Tahir
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Mostafa El Hammouchi' LIMIT 1), 2026, 1, '{"prime_equipe": 30.0, "absence_cp_jours": "2026-02-01"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Mostafa El Hammouchi
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Naoumi Boubker' LIMIT 1), 2026, 1, '{"heures_sup_25": "30 MIN", "prime_equipe": 30.0, "absence_cp_jours": "2026-02-01"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Naoumi Boubker
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Patrice Granger' LIMIT 1), 2026, 1, '{"commissions_ventes": 1492.0}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Patrice Granger
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Réquia Lgarch' LIMIT 1), 2026, 1, '{"absence_cp_jours": "2026-01-02"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Réquia Lgarch
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Saïd Daci' LIMIT 1), 2026, 1, '{"heures_sup_25": "15H", "prime_equipe": 30.0, "absence_cp_jours": "LE 2 LE 7 ET LE 30"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Saïd Daci
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Valentin Larguinho' LIMIT 1), 2026, 1, '{"heures_sup_25": "2H30", "prime_equipe": 30.0, "absence_cp_jours": "2026-02-01", "acompte_exceptionnel": 210.29}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Valentin Larguinho
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Alan Denis' LIMIT 1), 2026, 2, '{"augmentation_salaire": 258.0, "heures_sup_25": "1H30", "prime_equipe": 30.0}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Alan Denis
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Amine Hubert' LIMIT 1), 2026, 2, '{"heures_sup_25": "4H00", "information": "96H12 TRAVAILLE"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Amine Hubert
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Antoine Morel' LIMIT 1), 2026, 2, '{"augmentation_salaire": 150.0, "prime_equipe": "30 euros", "mi_temps_therapeutique": "80H"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Antoine Morel
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Bastien Vernisse' LIMIT 1), 2026, 2, '{"augmentation_salaire": 258.0, "heures_sup_25": "29H", "heures_sup_50": "6H", "heures_sup_nuit": "2H", "panier": 6.47, "prime_equipe": "30 euros"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Bastien Vernisse
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Cyril Cordonnier' LIMIT 1), 2026, 2, '{}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Cyril Cordonnier
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Djamal Bouferkas' LIMIT 1), 2026, 2, '{"augmentation_salaire": 150.0, "prime_equipe": 30.0, "absence_cp_jours": "14-20-26", "absence_justifiee_np_h": "15MIN DE RETARD"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Djamal Bouferkas
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Eugene Leconte' LIMIT 1), 2026, 2, '{"augmentation_salaire": 400.0}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Eugene Leconte
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Fatiha Mehdi' LIMIT 1), 2026, 2, '{"augmentation_salaire": 100.0, "acompte_exceptionnel": 450.15}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Fatiha Mehdi
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Grégory Desreumaux' LIMIT 1), 2026, 2, '{"absence_rtt": "2026-09-02"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Grégory Desreumaux
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Guillaume Granger' LIMIT 1), 2026, 2, '{"augmentation_salaire": 350.0, "commissions_ventes": 736.58}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Guillaume Granger
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Géraldine Themond' LIMIT 1), 2026, 2, '{"pret_sifa": 800.0}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Géraldine Themond
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Hamza Bachouchi' LIMIT 1), 2026, 2, '{"prime_equipe": "30 euros", "absence_css_jours": "LE 13/02"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Hamza Bachouchi
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Henri Mayeur' LIMIT 1), 2026, 2, '{"augmentation_salaire": 258.0, "prime_equipe": 30.0}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Henri Mayeur
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Jarod Vanhelstraeten' LIMIT 1), 2026, 2, '{"augmentation_salaire": 20.0, "mi_temps_therapeutique": "101H30"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Jarod Vanhelstraeten
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Jonathan Celisse' LIMIT 1), 2026, 2, '{"heures_sup_25": "17H30", "heures_sup_50": "18H00", "heures_sup_nuit": "5H00", "panier": 6.47, "prime_equipe": 30.0, "pret_sifa": 200.0}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Jonathan Celisse
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Joshua Mutombo' LIMIT 1), 2026, 2, '{"information": "94H08 TRAVAILLE"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Joshua Mutombo
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Laetitia Deffrenne' LIMIT 1), 2026, 2, '{}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Laetitia Deffrenne
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Laura Ratz' LIMIT 1), 2026, 2, '{"absence_maladie_jours": "TOUT LE MOIS"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Laura Ratz
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Laurent Woronin' LIMIT 1), 2026, 2, '{"augmentation_salaire": 153.0, "prime_equipe": 30.0, "absence_cp_jours": "19/2/2026"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Laurent Woronin
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Manuel Lesaffre' LIMIT 1), 2026, 2, '{"prime_objectifs": 400.0}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Manuel Lesaffre
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Maxime Allouchery' LIMIT 1), 2026, 2, '{"augmentation_salaire": 150.0, "heures_sup_25": "29H", "heures_sup_50": "2H30", "heures_sup_nuit": "1H", "panier": 6.47, "prime_equipe": "30 euros"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Maxime Allouchery
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Mickael Adyns' LIMIT 1), 2026, 2, '{"augmentation_salaire": 228.0, "prime_equipe": 30.0, "atd": 85.0, "acompte_exceptionnel": 900.3}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Mickael Adyns
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Mohamed Ali Tahir' LIMIT 1), 2026, 2, '{"heures_sup_25": "19H30", "prime_equipe": 30.0, "acompte_exceptionnel": 1200.3}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Mohamed Ali Tahir
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Mostafa El Hammouchi' LIMIT 1), 2026, 2, '{"augmentation_salaire": 200.0, "heures_sup_25": "6H", "prime_equipe": 30.0}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Mostafa El Hammouchi
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Naoumi Boubker' LIMIT 1), 2026, 2, '{"augmentation_salaire": 200.0, "heures_sup_25": "2H", "prime_equipe": 30.0}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Naoumi Boubker
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Patrice Granger' LIMIT 1), 2026, 2, '{"augmentation_salaire": 1600.0, "commissions_ventes": 1492.0}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Patrice Granger
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Réquia Lgarch' LIMIT 1), 2026, 2, '{}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Réquia Lgarch
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Saïd Daci' LIMIT 1), 2026, 2, '{"heures_sup_25": "8H30", "prime_equipe": 30.0}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Saïd Daci
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Tony Cathelineau' LIMIT 1), 2026, 2, '{"information": "70H TRAVAILLE"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Tony Cathelineau
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Valentin Larguinho' LIMIT 1), 2026, 2, '{"augmentation_salaire": 100.0, "heures_sup_25": "6H", "prime_equipe": 30.0, "absence_maladie_jours": "DU 16 AU 27", "acompte_exceptionnel": 400.0}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Valentin Larguinho
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Alan Denis' LIMIT 1), 2026, 3, '{"heures_sup_25": "3h30", "prime_equipe": 30.0, "absence_cp_jours": "2-11-23-24", "absence_css_jours": "25-26-27"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Alan Denis
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Amine Hubert' LIMIT 1), 2026, 3, '{}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Amine Hubert
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Antoine Morel' LIMIT 1), 2026, 3, '{"prime_equipe": "30 euros", "mi_temps_therapeutique": "88h"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Antoine Morel
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Bastien Vernisse' LIMIT 1), 2026, 3, '{"heures_sup_25": "16h30", "heures_sup_nuit": "6h30", "panier": 6.47, "prime_equipe": "30 euros"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Bastien Vernisse
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Cyril Cordonnier' LIMIT 1), 2026, 3, '{}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Cyril Cordonnier
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Djamal Bouferkas' LIMIT 1), 2026, 3, '{"prime_equipe": 30.0, "absence_css_jours": "le 30", "absence_non_justifie_h": "45 min le 27"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Djamal Bouferkas
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Eugene Leconte' LIMIT 1), 2026, 3, '{}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Eugene Leconte
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Fatiha Mehdi' LIMIT 1), 2026, 3, '{"acompte_exceptionnel": 200.0}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Fatiha Mehdi
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Grégory Desreumaux' LIMIT 1), 2026, 3, '{"prime_exceptionnelle": 200.0}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Grégory Desreumaux
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Guillaume Granger' LIMIT 1), 2026, 3, '{"commissions_ventes": 470.74, "absence_cp_jours": "le 27/02+2 et 3 mars"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Guillaume Granger
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Géraldine Themond' LIMIT 1), 2026, 3, '{"absence_cp_jours": "le 26", "pret_sifa": 800.0}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Géraldine Themond
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Hamza Bachouchi' LIMIT 1), 2026, 3, '{"prime_equipe": "30 euros", "absence_css_jours": "le 4 et le 27"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Hamza Bachouchi
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Henri Mayeur' LIMIT 1), 2026, 3, '{"prime_equipe": 30.0}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Henri Mayeur
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Jarod Vanhelstraeten' LIMIT 1), 2026, 3, '{"mi_temps_therapeutique": "112h51"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Jarod Vanhelstraeten
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Jonathan Celisse' LIMIT 1), 2026, 3, '{"heures_sup_25": "27h53", "heures_sup_nuit": "6h30", "panier": 6.47, "prime_equipe": 30.0}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Jonathan Celisse
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Laetitia Deffrenne' LIMIT 1), 2026, 3, '{}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Laetitia Deffrenne
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Laura Ratz' LIMIT 1), 2026, 3, '{"absence_maladie_jours": "tout le mois"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Laura Ratz
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Laurent Woronin' LIMIT 1), 2026, 3, '{"prime_equipe": 30.0}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Laurent Woronin
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Manuel Lesaffre' LIMIT 1), 2026, 3, '{"prime_objectifs": 400.0, "absence_cp_jours": "3 et 4"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Manuel Lesaffre
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Maxime Allouchery' LIMIT 1), 2026, 3, '{"heures_sup_25": "16h30", "heures_sup_nuit": "4h", "panier": 6.47, "prime_equipe": "30 euros", "absence_cp_jours": "le 2"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Maxime Allouchery
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Mickael Adyns' LIMIT 1), 2026, 3, '{"heures_sup_25": "30 min", "prime_equipe": 30.0, "absence_cp_jours": "du 02 au 11", "absence_css_jours": "le 20", "acompte_exceptionnel": 800.15}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Mickael Adyns
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Mohamed Ali Tahir' LIMIT 1), 2026, 3, '{"heures_sup_25": "29h", "prime_equipe": 30.0, "acompte_exceptionnel": 1100.15, "information": "Son brut a changé il passe à 2100 euros, il faut lui faire une régul de 150 euros brut concernant le mois de février qu''on avait pas mis"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Mohamed Ali Tahir
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Mostafa El Hammouchi' LIMIT 1), 2026, 3, '{"heures_sup_25": "18h", "prime_equipe": 30.0}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Mostafa El Hammouchi
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Naoumi Boubker' LIMIT 1), 2026, 3, '{"prime_equipe": 30.0, "absence_css_jours": "le 20"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Naoumi Boubker
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Patrice Granger' LIMIT 1), 2026, 3, '{"commissions_ventes": 1492.0}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Patrice Granger
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Réquia Lgarch' LIMIT 1), 2026, 3, '{}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Réquia Lgarch
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Saïd Daci' LIMIT 1), 2026, 3, '{"prime_equipe": 30.0}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Saïd Daci
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Tony Cathelineau' LIMIT 1), 2026, 3, '{"heures_sup_25": "20h30", "prime_equipe": "30 euros", "absence_maladie_jours": "du 9 au 13"}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Tony Cathelineau
INSERT OR IGNORE INTO paie_variables (user_id, annee, mois, data, updated_at, updated_by) VALUES ((SELECT id FROM users WHERE nom='Valentin Larguinho' LIMIT 1), 2026, 3, '{"heures_sup_25": "20h", "prime_equipe": 30.0, "absence_maladie_jours": "du 2 au 6", "acompte_exceptionnel": 500.0}', '2026-04-27T07:24:24.447829', 'import_historique');  -- Valentin Larguinho

COMMIT;
PRAGMA foreign_keys = ON;